export const ProjectData = [
    {
        id: 1,
        color: "#222831",
        name: "Jiheon Lee",
        type: "Personal",
        description: "Portfolio Page",
        date: "Summer 2022",
        language: ["HTML", "CSS", "ReactJS", "Framer Motion"],
        a: "https://github.com/SiruLee/sirulee.github.io",
    },
    {
        id: 2,
        color: "#3F4E4F",
        name: "Study Helper",
        type: "Assignment",
        description: "Clock, ToDo, and Flashcard",
        date: "Fall 2020 (Grade 11)",
        language: ["HTML", "CSS", "JavaScript"],
        a: "https://github.com/SiruLee/Study-Helper",
    },
    {
        id: 3,
        color: "#774360",
        name: "SparkNote",
        type: "Personal",
        description: "Notepad, Todo, Clock, and Weather",
        date: "Summer 2022",
        language: ["HTML", "CSS", "ReactJS", "Electron", "React Spring"],
        a: "https://github.com/SiruLee/SparkNote",
    },
    {
        id: 4,
        color: "#96897B",
        name: "StudyBuddy",
        type: "Course Project",
        description: "Campus Social Media Service",
        date: "Fall 2022",
        language: ["Java", "Git"],
        a: "https://github.com/CSC207-2022F-UofT/course-project-zuck-s-children",
    },
    {
        id: 5,
        color: "#4D455D",
        name: "Spinning Shapes",
        type: "Personal",
        description: "Spinning 3D shapes in ASCII",
        date: "Summer 2023",
        language: ["C++", "Linear Algebra", "Calculus"],
        a: "https://github.com/SiruLee/spinningShapes",
    },
    {
        id: 6,
        color: "#CFD2CF",
        name: "TBA",
        type: "???",
        description: "",
        date: "",
        language: [],
        a: "",
    },
];
